### PR TITLE
Fix #103

### LINKED ISSUE #103: Using Raw SQL the order by clause is case sensitive
When using raw sql the `order by` is case sensitive. Currently the library requires it to be lowercase. 

I ran into this issue and it was not clear what was happening at the time until I started debugging the library. 

You can see this behavior here: https://github.com/Elfocrash/Cosmonaut/blob/develop/src/Cosmonaut/Extensions/CosmosSqlQueryExtensions.cs#L41

### PR DESCRIPTION
**Pull request by tidusjar**
Fix the issue where we currently require the raw sql to have the `order by` in lowercase.

I could do a `.ToLower()`/`.ToUpper()` and that would also fix the issue, but that seems a bit more 'hacky'

### CODE REVIEW

**Comment by Elfocrash** [comment]
Thanks for spotting and fixing this. I have a question though. Are you sure this test is passing? Because after replacing it the `order by` should be lowercased, at least according to the code.

**Comment by Elfocrash** [comment]
Ok it turns out I was misusing Fluent Assertions. `Should().BeEquivelentTo()` is doing case insensitive checks.
That sucks. I need to change all the string comparisons to `Should().Be()` that actually checks the case too. That's why this test is passing even though it should fail.

**Comment by tidusjar** [comment]
Very good point, I have changed the expected to match what the code actually now does, and changed the assertions for that class.

**Comment by Elfocrash** [comment]
Thank you very much for this. Merged.

**Pull request merged**
